name: Build and Test
on: [push]
jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    container: docker://dstndstn/chime-frb-ci
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: chime-frb-ci
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: echo "pwd: $(pwd)"
      - run: ls /src
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - run: |
          gcc --version
          python --version
      - name: Set environment
        run: |
          # echo "BASE=$(pwd)" >> $GITHUB_ENV
          # echo "INCDIR=${BASE}/include" >> $GITHUB_ENV
          # echo "LIBDIR=${BASE}/lib" >> $GITHUB_ENV
          # echo "BINDIR=${BASE}/bin" >> $GITHUB_ENV
          # echo "PYDIR=${BASE}/lib/python2.7/site-packages" >> $GITHUB_ENV
          echo "$BINDIR" >> $GITHUB_PATH

      - name: Check out ch_frb_io
        uses: actions/checkout@v2
        with:
          repository: CHIMEFRB/ch_frb_io
          path: ch_frb_io
          ref: dstn-master
      - name: Build ch_frb_io
        run: |
          ls /src
          cd ch_frb_io
          ln -s site/Makefile.local.frb-compute-0 Makefile.local
          make -j8
          make install
      - name: Check out ch_frb_l1
        uses: actions/checkout@v2
        with:
          repository: kmsmith137/ch_frb_l1
          path: ch_frb_l1
          ref: dstn-master
      - name: Check out bonsai
        uses: actions/checkout@v2
        with:
          repository: kmsmith137/bonsai
          path: bonsai
          token: ${{ secrets.CHIME_ACCESS_TOKEN }}
          ref: dstn-master
